### ISSUE TITLE
_0xD5FE956C70FF370B

### ISSUE THREAD

**Issue by Gacsam** [alloc8or/rdr3-nativedb-data#60]
Not an issue, I just don't know how to note it down. 
Returns bool if player (or other ped) is crouched, including walking, running, climbing and dropping from low heights. (low = no ragdoll effect). True = Crouched. I think it's GET_PED_CROUCH_MOVEMENT

**Comment by Disquse** [comment]
This native was documented by in Cfx.re discord guild. And it was documented here as well.

**Comment by Gacsam** [comment]
> This native was documented by in Cfx.re discord guild. And it was documented here as well.

Oops, my bad, didn't seem to find it on rdr-mods and thought it's using this database, apologies.
