### ISSUE TITLE
A few other hashes

### ISSUE THREAD

**Issue by iamdroppy** [alloc8or/rdr3-nativedb-data#85]
**SCRIPTS::_SHOW_LOADING_SCREEN** 
Hash: 0x1E5B70E53DB661E5

Usage `RDR2.Native.Function.Call(0x1E5B70E53DB661E5, 0, 0, 0, "Big Text", "TITLE", "SUBTITLE");` 

`Hash p0, Hash p1, Hash p2, const char* gamemodeName, const char* title, const char* subtitle`

I'll be doing a  PR later if you find better.

This one has already been tested. Call it once and it will be on a loading screen until shutdown, which I'm trying to implement (possibly the one below).

**SCRIPTS::SHUTDOWN_LOADING_SCREEN** 
Still unsure/untested

Hash: 0x1E5B70E53DB661E5

Usage `RDR2.Native.Function.Call(0x1E5B70E53DB661E5);` 

Not quite sure if it works - been using but it doesn't seem to have any effect. RDR2-MODS still have it in there at https://www.rdr2mods.com/nativedb/index/scripts/shutdown_loading_screen-r5024/

**All screen loading scripts according to rdr2mods**

I haven't tested but should be easy enough if a hand is needed.

**SCRIPTS**

BOOL GET_NO_LOADING_SCREEN ()  //0x323DAF00687E0F28

void _SHOW_LOADING_SCREEN ( Hash p0, Hash p1, Hash p2, const char* gamemodeName, const char* title, const char* subtitle )  //0x1E5B70E53DB661E5

void SHUTDOWN_LOADING_SCREEN ()  //0xFC179D7E8886DADF

void SET_NO_LOADING_SCREEN ( BOOL toggle )  //0x5CB83156AA038F95

BOOL _IS_LOADING_SCREEN_ACTIVE ()  //0xB54ADBE65D528FCB

**DLC**

BOOL GET_IS_LOADING_SCREEN_ACTIVE ()  //0x71D4BF5890659B0C

**HUD**

void HIDE_LOADING_ON_FADE_THIS_FRAME ()  //0xEA600AABAF4B9084

**Comment by alloc8or** [comment]
I'm not sure what this issue is about, to be honest. All of those are already documented (since 2019!).

**Comment by alloc8or** [comment]
I'm just gonna close this for now. If you think I missed anything, feel free to submit another issue/PR.
